# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head><title>Custom NGINX Page</title></head>
      <body><h1>Hello from version 0.2.0!</h1></body>
    </html>
